/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interprete;

/**
 *
 * @author M Express
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butAcerca = new javax.swing.JButton();
        butAyuda = new javax.swing.JButton();
        butSeleccionar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        combOperacion = new javax.swing.JComboBox<>();
        butTempTable = new javax.swing.JButton();
        butRename = new javax.swing.JButton();
        butSalir = new javax.swing.JButton();
        butRegresar = new javax.swing.JButton();
        butCruzada = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butAcerca.setText("Acerca De");

        butAyuda.setText("Ayuda");

        butSeleccionar.setText("Seleccionar");
        butSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        combOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Select", "Proyección", "Unión", "Diferencia de Conjuntos", "Intersección", "Division", "Join", "Natural Join", "Agregación", "Agrupación", "Producto Cartesiano", "Renombrar" }));
        combOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combOperacionActionPerformed(evt);
            }
        });

        butTempTable.setText("Ver Tablas Temporales");

        butRename.setText("Renombrar");

        butSalir.setText("Salir");
        butSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSalirActionPerformed(evt);
            }
        });

        butRegresar.setText("Regresar");
        butRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegresarActionPerformed(evt);
            }
        });

        butCruzada.setText("Ver Tablas Cruzadas");

        jLabel1.setText("Consultas");

        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(butAcerca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butAyuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(butSalir))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butSeleccionar)
                        .addGap(56, 56, 56))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(butTempTable)
                                .addGap(18, 18, 18)
                                .addComponent(butCruzada)
                                .addGap(18, 18, 18)
                                .addComponent(butRename))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butAcerca)
                    .addComponent(butAyuda)
                    .addComponent(butSalir))
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butSeleccionar)
                    .addComponent(combOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butTempTable)
                    .addComponent(butRename)
                    .addComponent(butCruzada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butRegresar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combOperacionActionPerformed

    private void butSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSeleccionarActionPerformed
        // TODO add your handling code here:
        if(combOperacion.getSelectedItem().toString()==""){}
        if(combOperacion.getSelectedItem().toString()=="Select"){
            Op_Select VSelect = new Op_Select();
            VSelect.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Proyección"){
            Op_Proyeccion VProyect = new Op_Proyeccion();
            VProyect.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Unión"){
            Op_Union VUnion = new Op_Union();
            VUnion.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Diferencia de Conjuntos"){
            Op_Diferencia VDiferencia = new Op_Diferencia();
            VDiferencia.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Intersección"){
            Op_iInterseccion VInter = new Op_iInterseccion();
            VInter.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Division"){
            Op_Division VDivision = new Op_Division();
            VDivision.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Join"){
            Op_Join VJoin = new Op_Join();
            VJoin.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Natural Join"){
            Op_NaturalJoin VNJoin = new Op_NaturalJoin();
            VNJoin.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Agregación"){
            Op_Agregacion VAgregacion = new Op_Agregacion();
            VAgregacion.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Agrupación"){
            Op_Agrupacion VAgrupacion = new Op_Agrupacion();
            VAgrupacion.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Producto Cartesiano"){
            Op_ProductoCartesiano Vpc = new Op_ProductoCartesiano();
            Vpc.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Renombrar"){
            Op_Renombrar VRenombrar = new Op_Renombrar();
            VRenombrar.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_butSeleccionarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Inicio VInicio = new Inicio();
        VInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void butSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_butSalirActionPerformed

    private void butRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegresarActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal VPrincipal = new VentanaPrincipal();
        VPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_butRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAcerca;
    private javax.swing.JButton butAyuda;
    private javax.swing.JButton butCruzada;
    private javax.swing.JButton butRegresar;
    private javax.swing.JButton butRename;
    private javax.swing.JButton butSalir;
    private javax.swing.JButton butSeleccionar;
    private javax.swing.JButton butTempTable;
    private javax.swing.JComboBox<String> combOperacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
