/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interprete;

/**
 *
 * @author M Express
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    private String usuario;
    
    public Consultas() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public String getUsuario (){
         return usuario;
    }

    public void setUsuario (String variable){
        this.usuario = variable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butAcerca = new javax.swing.JButton();
        butAyuda = new javax.swing.JButton();
        butSeleccionar = new javax.swing.JButton();
        combOperacion = new javax.swing.JComboBox<>();
        butSalir = new javax.swing.JButton();
        butRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        butAcerca.setText("Acerca De");
        butAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAcercaActionPerformed(evt);
            }
        });

        butAyuda.setText("Ayuda");

        butSeleccionar.setText("Seleccionar");
        butSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSeleccionarActionPerformed(evt);
            }
        });

        combOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Select", "Proyección", "Unión", "Diferencia de Conjuntos", "Intersección", "Division", "Join", "Natural Join", "Agregación", "Agrupación", "Producto Cartesiano", "Renombrar" }));
        combOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combOperacionActionPerformed(evt);
            }
        });

        butSalir.setText("Salir");
        butSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSalirActionPerformed(evt);
            }
        });

        butRegresar.setText("Regresar");
        butRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Consultas");

        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butRegresar)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addComponent(butAcerca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butAyuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(butSalir))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(combOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(butSeleccionar))
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butAcerca)
                    .addComponent(butAyuda)
                    .addComponent(butSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butSeleccionar)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butRegresar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combOperacionActionPerformed

    private void butSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSeleccionarActionPerformed
        // TODO add your handling code here:
        if(combOperacion.getSelectedItem().toString()==""){}
        if(combOperacion.getSelectedItem().toString()=="Select"){
            Op_Select VSelect = new Op_Select();
            VSelect.setUsuario(usuario);
            VSelect.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Proyección"){
            Op_Proyeccion VProyect = new Op_Proyeccion();
            VProyect.setUsuario(usuario);
            VProyect.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Unión"){
            Op_Union VUnion = new Op_Union();
            VUnion.setUsuario(usuario);
            VUnion.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Diferencia de Conjuntos"){
            Op_Diferencia VDiferencia = new Op_Diferencia();
            VDiferencia.setUsuario(usuario);
            VDiferencia.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Intersección"){
            Op_iInterseccion VInter = new Op_iInterseccion();
            VInter.setUsuario(usuario);
            VInter.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Division"){
            Op_Division VDivision = new Op_Division();
            VDivision.setUsuario(usuario);
            VDivision.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Join"){
            Op_Join VJoin = new Op_Join();
            VJoin.setUsuario(usuario);
            VJoin.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Natural Join"){
            Op_NaturalJoin VNJoin = new Op_NaturalJoin();
            VNJoin.setUsuario(usuario);
            VNJoin.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Agregación"){
            Op_Agregacion VAgregacion = new Op_Agregacion();
            VAgregacion.setUsuario(usuario);
            VAgregacion.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Agrupación"){
            Op_Agrupacion VAgrupacion = new Op_Agrupacion();
            VAgrupacion.setUsuario(usuario);
            VAgrupacion.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Producto Cartesiano"){
            Op_ProductoCartesiano Vpc = new Op_ProductoCartesiano();
            Vpc.setUsuario(usuario);
            Vpc.setVisible(true);
            this.setVisible(false);
        }
        if(combOperacion.getSelectedItem().toString()=="Renombrar"){
            Op_Renombrar VRenombrar = new Op_Renombrar();
            VRenombrar.setUsuario(usuario);
            VRenombrar.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_butSeleccionarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Inicio VInicio = new Inicio();
        VInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void butSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_butSalirActionPerformed

    private void butRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegresarActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal VPrincipal = new VentanaPrincipal();
        VPrincipal.setUsuario(this.usuario);
        VPrincipal.activar();
        VPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_butRegresarActionPerformed

    private void butAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAcercaActionPerformed
        // TODO add your handling code here:
        AcercaDe VAcerca = new AcercaDe();
        VAcerca.setVisible(true);
    }//GEN-LAST:event_butAcercaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAcerca;
    private javax.swing.JButton butAyuda;
    private javax.swing.JButton butRegresar;
    private javax.swing.JButton butSalir;
    private javax.swing.JButton butSeleccionar;
    private javax.swing.JComboBox<String> combOperacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
